# -*- coding: utf-8 -*-
"""First_Difference_Equations_Modeling_Challenge_firstversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fpHF2vgk2a3BcZdpAq0nqBbIhFkEyCV

# Universidad del Rosario
# Modeling of dynamical systems
# First Difference Equations Modeling Challenge - 20/08/2023
Jham Pool Murillo, Camila Patarroyo, Nicolás Dussan, Ángel López
"""

# Import the necessary libraries
import pandas as pd
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'browser'


def corruption_model_discrete(budget, corruption_rate, population_needs, investment_efficiency, num_steps):
    budget_history = [budget]
    population_needs_history = [population_needs]

    for _ in range(num_steps):
        next_budget = 1 # Falta definir la función
        next_population_needs = 1 # Falta definir la función

        budget = next_budget
        population_needs = next_population_needs

        budget_history.append(budget)
        population_needs_history.append(population_needs)

    return budget_history, population_needs_history


# Initial parameters
initial_budget = 1000000
corruption_rate = 0.7
population_needs = 1750000000
investment_efficiency = 0.05
nsteps = 1000

# Simulating the model
budget_history, population_needs_history = corruption_model_discrete(initial_budget, corruption_rate,
                                                                    population_needs, investment_efficiency,
                                                                    nsteps)

# Falta hacer la simulación...

# Creating the plot
# fig.show(renderer='colab')